name: Deploy images to Docker Hub
on: [push, workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with: { load: true, tags: "scaffoldeducation/kubectl:latest" }

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main' && github.repository == 'scaffoldeducation/kubectl'
        with: { username: "${{ secrets.DOCKERHUB_USERNAME }}", password: "${{ secrets.DOCKERHUB_PASSWORD }}" }

      - name: Build and push
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main' && github.repository == 'scaffoldeducation/kubectl'
        with: { push: true, tags: "scaffoldeducation/kubectl:latest" }
